### ISSUE TITLE
Domain Layer 추가 및 데이터 레이어 재설계

### ISSUE THREAD

**Issue by DoTheBestMayB** [DoTheBestMayB/Zipbab#16]
## 구현 사항
- [x] 변경된 UI에 따라 데이터 모델 재정의
- [x] DataSource 추가 및 Firestore API 사용 코드 수정
- [x] retrofit + moshi 에서 ktor + kotlinx.serialization으로 수정
- [x] domain Layer 추가
- [x] 비밀번호 암호화
- [x] Firesbase storage에 있는 이미지를 token을 포함한 URL로 가져오는 것이 아니라, path를 이용해 안전하게 사용하도록 수정

## TODO
- [ ] App 모듈 수정하기
- [ ] off-line first 구현(로그인한 사용자 정보를 위한 Entity 선언과 Room 설정만 하고, API 응답 결과와 Room 저장을 잇지는 않았음)
