### ISSUE TITLE
사용자의 신뢰성을 나타낼 수 있는 요소 추가

### ISSUE THREAD

**Issue by DoTheBestMayB** [DoTheBestMayB/Zipbab#5]
## Feedback

- 함께 모임을 하게 될 사람이 믿을 만한 사람인지 확인할 수 있는 개인 인증, 시스템이 있으면 좋겠다.
- 서로 모르는 사람들이 모이는 서비스 이기 때문에, 모임원에 대한 신뢰성이 가장 중요할 것 같습니다. 신뢰성을 확인하기 위한 장치는 어떤 것이 있나요?

## TODO

- [ ] 사용자 인증 시스템 도입
  - 이메일 인증
  - 동네 위치 인증
  - 전화번호 인증
- [ ] 실제 모임에 참석했는지 확인하기 위한 시스템 도입
  - Host가 QR 코드 생성하고, 다른 참여 인원이 Host의 QR 코드 찍어서 인증하는 방식
  - QR 생성 및 인증을 위해 모임 반경 ~ 2km 내에 위치해야 함
  - QR 정보는 서버에서 생성 후 Host에 보내주며, 다른 사용자가 인증한 QR이 서버 QR과 동일한지 검증
  - Fake GPS 탐지 기능 추가
- [ ] 모임 비공개 처리 기능 구현
  - 지문 또는 패턴으로 풀어야 확인 가능
